import Head from 'next/head';


// Import the shared function into the Next.js application
import { getSiteInfo, addNumber } from 'site-info';

export default function Home() {
  let siteInfo = getSiteInfo(); //Define a variable to get the values
  let r = addNumber(3, 4);
  return (
    <div >
      <Head>
        <title>{siteInfo.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Output the site title and subtitle to the screen*/}
      <main >
        <h1 >Welcome to {siteInfo.title}</h1>
        <p >{siteInfo.subtitle}</p>
        <p>your add result is: {r}</p>
      </main>
    </div>
  );
}